# Generated by Django 5.1.7 on 2025-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
