# Generated by Django 5.1 on 2025-05-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic key-value pairs for product features.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
