# Generated by Django 5.1 on 2025-05-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_custom_attributes_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
