# Generated by Django 5.1 on 2025-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt1',
            field=models.ImageField(blank=True, help_text='Alternative product image 1.', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt2',
            field=models.ImageField(blank=True, help_text='Alternative product image 2.', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt3',
            field=models.ImageField(blank=True, help_text='Alternative product image 3.', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt4',
            field=models.ImageField(blank=True, help_text='Alternative product image 4.', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, help_text='Main product image.', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
