# Generated by Django 5.1 on 2025-06-05 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response_type', models.CharField(choices=[('product', 'Product Related'), ('general', 'General Question'), ('purchase', 'Purchase Intent'), ('support', 'Customer Support')], max_length=50)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('found_products', models.IntegerField(default=0)),
                ('showed_whatsapp', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'Site Information', 'verbose_name_plural': 'Site Information'},
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this setting does'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
